import AboutMain from "@/Components/AboutMain";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "School Chale Ham | About",
  description: "Generated by create next app",
};

export default function about () {
  return(
    <AboutMain />
  )
}