import ContactUsMain from "@/Components/ContactUsMain";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "School Chale Ham | Contact US",
    description: "Generated by create next app",
  };
  
export default function Contact () {
    return(
        <ContactUsMain />
    )
}