import { Academics } from "@/Components/Academics";
import { ContributeSection } from "@/Components/ContributeSection";
import HomeBanner from "@/Components/HomeBanner";
import { InSpotlight } from "@/Components/InSpotlight";
import { NewsLater } from "@/Components/NewsLater";
import { Partners } from "@/Components/Partners";
import { Metadata } from "next";
import icon from "@/app/favicon.ico"

export const metadata: Metadata = {
  title: "School Chale Ham | Home",
  description: "Generated by create next app",
};

export default function Home() {
  
  return (
    <>
      <HomeBanner />
      <InSpotlight />
      <NewsLater />
      <Academics />
      <Partners />
      <ContributeSection />
    </>
  );
}
