"use client"
import { useAppContext } from "@/context-api/AppContext";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "School Chale Ham | About",
  description: "Generated by create next app",
};
export default function AboutMain() {
    const { language } = useAppContext()
    return (
      <>
      <div className="max-w-4xl mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold text-center mb-4">{language === "English" ? "About Us" : "हमारे बारे में"}</h1>
            <div className="text-lg text-gray-700">
                {
                    language === "English" ?
                      <div>
                        Welcome to &quot;<strong>School Chale Ham</strong>&quot;! We&apos;re dedicated to redefining K-12 education and inspiring a new generation of learners. Our platform fosters creativity, innovation, and excellence in education, empowering students to achieve their full potential, celebrate their accomplishments, and drive positive change in their communities. Join us as we share inspiring stories, promote educational opportunities, and build a supportive community for students, parents, and educators.
                        <br/><br/>
                        <strong>Our Vision</strong>
                        <br/>
                        We envision a world where every student has access to the quality education, opportunities for growth, and the support they need to thrive. Through our initiatives and partnerships, we strive to create a network of resources and support for students from all backgrounds, promote equity and inclusivity in education, and inspire a new generation of leaders and innovators. This is just the beginning – stay tuned as we unveil a plethora of innovative initiatives aimed at revolutionizing school education.
                        <br/><br/>
                        <strong>Our Vision for the Future</strong>
                        <br/>
                        This is just the beginning – stay tuned as we unveil a plethora of innovative initiatives aimed at revolutionizing school education. As we continue to grow, we are committed to exploring new avenues and introducing exciting projects that will shape the future of School Education. Join us on this journey of transformation and empowerment.
                        <br/><br/>
                        <strong>Our Values</strong>
                        <ul>
                          <li><strong>Excellence:</strong> We are committed to upholding the highest standards of quality, integrity, and professionalism in everything we do.</li>
                          <li><strong>Empowerment:</strong> We empower students to take control of their education, pursue their passions, and make a positive impact in their communities.</li>
                          <li><strong>Inclusivity:</strong> We embrace diversity, equity, and inclusion, recognizing the unique strengths and contributions of every individual.</li>
                          <li><strong>Collaboration:</strong> We believe in the power of collaboration and partnership, working together to achieve shared goals and create meaningful change.</li>
                        </ul>
                        <br/>
                        <strong>Join Us</strong>
                        <br/>
                        Join us on our journey to inspire, empower, and transform lives through education. Together, we can make a difference and create a brighter future for generations to come. For inquiries, collaborations, or to join our mission, reach out to us at <strong><a href="mailto:teamsch.connect@gmail.com">teamsch.connect@gmail.com</a></strong>.
                      </div>
                    :
                      <div>
                        स्वागत है &quot;<strong>School Chale Ham</strong>&quot; में! हम K-12 शिक्षा को पुनर्निर्भारित करने और नए शिक्षार्थियों की एक नई पीढ़ी को प्रेरित करने में समर्थ हैं। हमारा प्लेटफ़ॉर्म शिक्षा में रचनात्मकता, नवाचार, और उत्कृष्टता को बढ़ावा देता है, छात्रों को उनकी पूरी क्षमता तक पहुँचाने, उनकी उपलब्धियों का समर्थन करने, और उनकी समुदायों में सकारात्मक परिवर्तन को बढ़ावा देता है। हमें जुड़िये जब हम प्रेरणादायक कहानियाँ साझा करते हैं, शैक्षिक अवसरों को प्रमोट करते हैं, और छात्रों, माता-पिता, और शिक्षकों के लिए एक सहायक समुदाय बनाते हैं।
                        <br/><br/>
                        <strong>हमारा दृष्टिकोण</strong>
                        <br/>
                        हम एक ऐसे विश्व की दृष्टि रखते हैं जहाँ प्रत्येक छात्र को गुणवत्ता की शिक्षा, वृद्धि के अवसर, और समर्थन मिलता है जो उन्हें अपने स्वप्नों की पूर्ति के लिए ज़रूरी होता है। हमारे पहल और साझेदारियों के माध्यम से, हम छात्रों के लिए संसाधनों और समर्थन का एक नेटवर्क बनाने का प्रयास करते हैं, शिक्षा में समानता और समावेश को प्रोत्साहित करते हैं, और एक नए पीढ़ी के नेताओं और नवाचारियों को प्रेरित करते हैं। यह सिर्फ शुरुआत है - हम आगे और भी कई अद्भुत पहल करने वाले हैं जो शिक्षा के क्षेत्र में नया आयाम देने की दिशा में होंगी।
                        <br/><br/>
                        <strong>हमारे मूल्य</strong>
                        <ul>
                            <li><strong>उत्कृष्टता:</strong> हम अपने काम में उच्चतम मानकों का पालन करने के लिए समर्पित हैं, जोड़ी, और पेशेवरता करते हैं।</li>
                            <li><strong>सशक्तिकरण:</strong> हम छात्रों को अपने शिक्षा पर नियंत्रण लेने, अपने शौकों का पीछा करने, और अपने समुदायों में सकारात्मक प्रभाव डालने के लिए सशक्त करते हैं।</li>
                            <li><strong>समावेश:</strong> हम विविधता, न्याय, और समावेश को गले मिलाते हैं, प्रत्येक व्यक्ति की अद्वितीय शक्तियों और योगदान को मानते हैं।</li>
                            <li><strong>सहयोग:</strong> हम सहयोग और साझेदारी की शक्ति में विश्वास रखते हैं, साझा लक्ष्यों को हासिल करने और मानवीय परिवर्तन को साकार करने के लिए मिलकर काम करते हैं।</li>
                        </ul>
                        <br/>
                        <strong>हमारे साथ जुड़ें</strong>
                        <br/>
                        शिक्षा के माध्यम से जीवनोत्साहित, सशक्तित, और परिवर्तित करने के हमारे सफ़र में हमारे साथ जुड़ें। साथ में हम एक बदलाव का साथी बना सकते हैं और आने वाली पीढ़ियों के लिए एक उज्जवल भविष्य बना सकते हैं। किसी भी पूछताछ, सहयोग, या हमारे मिशन में शामिल होने के लिए, हमसे <strong><a href="mailto:teamsch.connect@gmail.com">teamsch.connect@gmail.com</a></strong> पर संपर्क करें।
                      </div>
                }
            </div>
      </div></>
    );
  }
  