import BlogGridSection from "@/Components/BLogListingMain"
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "School Chale Ham | Blogs",
    description: "Generated by create next app",
  };

export default function Blogs () {
    return(
        <BlogGridSection />
    )
}